import { describe, expect, it } from "vitest";
import { BackendRegistry, eventBase, type AgentAdapter, type Runtime, type Session } from "@session-master/core";
import { SessionService } from "./service.js";

const session: Session = { id: "mock:one", backendId: "mock", title: "Fix cache", projectName: "repo", cwd: "/tmp", status: "idle" };
const runtime: Runtime = { id: "runtime", sessionId: session.id, backendId: "mock", cwd: "/tmp", startedAt: new Date().toISOString(), status: "running", transport: "structured", host: "local" };
const adapter: AgentAdapter = { id: "mock", name: "Mock", capabilities: { discoverSessions: true, readHistory: true, nativeResume: true, structuredEvents: true, terminalStreaming: true, sendMessage: true, permissions: false, stop: true, crossAgentContinue: true }, detect: async () => ({ installed: true, available: true }), listSessions: async () => [session], getSession: async () => session, getHistory: async () => [{ ...eventBase(session.id, "mock"), type: "user_message", content: "hello" }], start: async () => runtime, resume: async () => runtime, sendMessage: async () => {}, stop: async () => {}, subscribe: () => () => {} };
const store = { upsertSessions: () => {}, recordContinuation: () => {} };

describe("SessionService", () => {
  it("discovers, filters and resumes sessions", async () => { const registry = new BackendRegistry(); registry.register(adapter); const service = new SessionService(registry, store as never); await service.refresh(); expect((await service.list({ query: "cache" }))).toHaveLength(1); expect((await service.resume(session.id)).status).toBe("running"); });
  it("keeps the managed runtime visible after resume and refresh", async () => { const registry = new BackendRegistry(); registry.register(adapter); const service = new SessionService(registry, store as never); await service.refresh(); await service.resume(session.id); expect((await service.list())[0]).toMatchObject({ runtimeId: runtime.id, status: "waiting_input" }); await service.refresh(); expect((await service.list())[0]).toMatchObject({ runtimeId: runtime.id, status: "waiting_input" }); });
  it("keeps a newly started runtime in the immediately returned session list", async () => { const registry = new BackendRegistry(); registry.register(adapter); const service = new SessionService(registry, store as never); await service.refresh(); await service.start("mock", "/tmp", "Run tests"); expect((await service.list()).find((item) => item.id === runtime.sessionId)?.status).toBe("running"); });
  it("clears the runtime after stopping and treats repeated stops as success", async () => { const registry = new BackendRegistry(); registry.register(adapter); const service = new SessionService(registry, store as never); await service.refresh(); await service.start("mock", "/tmp", "Run tests"); await service.stop(runtime.id); const stopped = (await service.list()).find((item) => item.id === runtime.sessionId); expect(stopped?.status).toBe("completed"); expect(stopped?.runtimeId).toBeUndefined(); await expect(service.stop(runtime.id)).resolves.toBeUndefined(); });
  it("keeps the runtime active when the backend process does not stop", async () => { const registry = new BackendRegistry(); registry.register({ ...adapter, stop: async () => { throw new Error("process still running"); } }); const service = new SessionService(registry, store as never); await service.refresh(); await service.start("mock", "/tmp", "Run tests"); await expect(service.stop(runtime.id)).rejects.toThrow("process still running"); const active = (await service.list()).find((item) => item.id === runtime.sessionId); expect(active?.status).toBe("running"); expect(active?.runtimeId).toBe(runtime.id); });
});
